name: Frontend CI/CD (Uptime Kuma)

on:
  push:
    branches: ["master"]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    env:
      HOST_IP: ${{ secrets.FRONTEND_SERVER_IP }}
      HOST_USER: ubuntu

    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      - name: 2. Build Step (Placeholder)
        run: echo "building frontend application..."

      - name: 4. Deployment via SSH to Frontend Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.HOST_IP }}
          username: ${{ env.HOST_USER }}
          key: ${{ secrets.FRONTEND_SSH_KEY }}
          script: |
            sudo apt update -y

            cat <<EOF > docker-compose.yml
            services:
              uptime-kuma:
                image: louislam/uptime-kuma:2
                restart: unless-stopped
                volumes:
                  - ./data:/app/data
                ports:
                  - "3001:3001"
            EOF
            #sudo docker compose -f docker-compose.yml down
            docker stop $(docker ps -q)
            sleep 5
            sudo docker compose -f docker-compose.yml up -d
            echo "Deployment of Uptime Kuma complete."
